export const mediaItems = [
  { id: 1, type: 'photo', src: 'src/assets/1.jpg', caption: 'Помнишь, как мы гуляли?' },
  { id: 2, type: 'photo', src: 'src/assets/2.jpg', caption: 'А снежного ангела?' },
  { id: 3, type: 'photo', src: 'src/assets/3.jpg', caption: 'Тут впервые ко мне за руль села' },
  { id: 4, type: 'photo', src: 'src/assets/4.jpg', caption: 'Не ехала а все равно сломала' },
  { id: 5, type: 'video', src: '/videos/5.mp4', caption: 'А тут уже катаемя вместе' },
  { id: 6, type: 'video', src: '/videos/6.mp4', caption: 'И поем' },
  { id: 7, type: 'photo', src: 'src/assets/7.jpg', caption: 'На стиле' },
  { id: 8, type: 'video', src: '/videos/8.mp4', caption: 'Идешь домой' },
  { id: 9, type: 'video', src: '/videos/9.mp4', caption: 'Бесишься' },
  { id: 10, type: 'photo', src: 'src/assets/10.jpg', caption: 'Селфи в наушниках моих' },
  { id: 11, type: 'photo', src: 'src/assets/11.jpg', caption: 'Целуемся' },
  { id: 12, type: 'photo', src: 'src/assets/12.jpg', caption: 'Продолжаем' },
  { id: 13, type: 'photo', src: 'src/assets/13.jpg', caption: 'Цветы подарил' },
  { id: 14, type: 'photo', src: 'src/assets/14.jpg', caption: 'Довольная' },
  { id: 15, type: 'photo', src: 'src/assets/15.jpg', caption: 'Недовольная' },
  { id: 16, type: 'photo', src: 'src/assets/16.jpg', caption: 'И снова довольная' },
  { id: 17, type: 'video', src: '/videos/17.mp4', caption: 'Сердечко мне делаешь' },
  { id: 18, type: 'photo', src: 'src/assets/18.jpg', caption: 'Д' },
  { id: 19, type: 'photo', src: 'src/assets/19.jpg', caption: 'Глаз твой' },
  { id: 20, type: 'photo', src: 'src/assets/20.jpg', caption: 'Повар в деле' },
  { id: 21, type: 'photo', src: 'src/assets/21.jpg', caption: 'Еще цветы' },
  { id: 22, type: 'photo', src: 'src/assets/22.jpg', caption: 'И книжка' },
  { id: 23, type: 'photo', src: 'src/assets/23.jpg', caption: 'Время мне показываешь' },
  { id: 24, type: 'photo', src: 'src/assets/24.jpg', caption: 'И уже абьюзишь' },
  { id: 25, type: 'photo', src: 'src/assets/25.jpg', caption: 'Потом кривляешься' },
  { id: 26, type: 'photo', src: 'src/assets/26.jpg', caption: 'И с Сабиной тоже' },
  { id: 27, type: 'photo', src: 'src/assets/27.jpg', caption: 'И со мной' },
  { id: 28, type: 'photo', src: 'src/assets/28.jpg', caption: 'Чтоб меня лучше видела' },
  { id: 29, type: 'photo', src: 'src/assets/29.jpg', caption: 'Красуешься' },
  { id: 30, type: 'photo', src: 'src/assets/30.jpg', caption: 'На катке' },
  { id: 31, type: 'video', src: '/videos/31.mp4', caption: 'Ну красотка' },
  { id: 32, type: 'photo', src: 'src/assets/32.jpg', caption: 'Ждешь меня в машие' },
  { id: 33, type: 'photo', src: 'src/assets/33.jpg', caption: 'Пися' },
  { id: 34, type: 'photo', src: 'src/assets/34.jpg', caption: 'Лежим' },
  { id: 35, type: 'photo', src: 'src/assets/35.jpg', caption: 'Это я целовал' },
  { id: 36, type: 'photo', src: 'src/assets/36.jpg', caption: 'А тут не целовал' },
  { id: 37, type: 'photo', src: 'src/assets/37.jpg', caption: 'Уехала и все - капец' },
  { id: 38, type: 'photo', src: 'src/assets/38.jpg', caption: 'Приехала и гуляем' },
  { id: 39, type: 'photo', src: 'src/assets/39.jpg', caption: 'Кушаешь' },
  { id: 40, type: 'photo', src: 'src/assets/40.jpg', caption: 'Кушаешь' },
  { id: 41, type: 'photo', src: 'src/assets/41.jpg', caption: 'Кушаешь' },
  { id: 42, type: 'photo', src: 'src/assets/42.jpg', caption: 'Поела' },
  { id: 43, type: 'photo', src: 'src/assets/43.jpg', caption: 'Спорт - начало' },
  { id: 44, type: 'photo', src: 'src/assets/44.jpg', caption: 'Тренируешься' },
  { id: 45, type: 'photo', src: 'src/assets/45.jpg', caption: 'Тренируешься' },
  { id: 46, type: 'photo', src: 'src/assets/46.jpg', caption: 'Тренируешься' },
  { id: 47, type: 'photo', src: 'src/assets/47.jpg', caption: 'Тренируемся' },
  { id: 48, type: 'photo', src: 'src/assets/48.jpg', caption: 'Самое крутое фото' },
  { id: 49, type: 'photo', src: 'src/assets/49.jpg', caption: 'Второе самое крутое фото' },
  { id: 50, type: 'photo', src: 'src/assets/50.jpg', caption: 'Тут что-то снова недовольная' },
  { id: 51, type: 'photo', src: 'src/assets/51.jpg', caption: 'А тут довольная' },
  { id: 52, type: 'photo', src: 'src/assets/52.jpg', caption: 'Котик' },
  { id: 53, type: 'photo', src: 'src/assets/53.jpg', caption: 'Сидишь такая вся крутая' },
  { id: 54, type: 'photo', src: 'src/assets/54.jpg', caption: 'Ну как без бабл ти' },
  { id: 55, type: 'photo', src: 'src/assets/55.jpg', caption: 'Собралась вся такая красивая' },
  { id: 56, type: 'photo', src: 'src/assets/56.jpg', caption: 'Домой спать' },
  { id: 57, type: 'photo', src: 'src/assets/57.jpg', caption: 'Сфоткались после тренировки' },
  { id: 58, type: 'photo', src: 'src/assets/58.jpg', caption: 'Едешь на машине' },
  { id: 59, type: 'photo', src: 'src/assets/59.jpg', caption: 'А тут пешком' },
  { id: 60, type: 'photo', src: 'src/assets/60.jpg', caption: 'Тони Старк собрал мини-реактор сидя в яме... ИЗ МЕТАЛЛОЛОМА' },
  { id: 61, type: 'photo', src: 'src/assets/61.jpg', caption: 'Еще с комикона' },
  { id: 62, type: 'photo', src: 'src/assets/62.jpg', caption: 'Не дал им тебя отвоевать' },
  { id: 63, type: 'photo', src: 'src/assets/63.jpg', caption: 'Сидишь заказ ждешь' },
  { id: 64, type: 'photo', src: 'src/assets/64.jpg', caption: 'Поела и гулять пошла' },
  { id: 65, type: 'photo', src: 'src/assets/65.jpg', caption: 'Внезапный дэб' },
  { id: 66, type: 'photo', src: 'src/assets/66.jpg', caption: 'Отвлекаешь меня от тренировки' },
  { id: 67, type: 'photo', src: 'src/assets/67.jpg', caption: 'Не наш' },
  { id: 68, type: 'photo', src: 'src/assets/68.jpg', caption: 'Красотка' },
  { id: 69, type: 'photo', src: 'src/assets/69.jpg', caption: 'Сидит в моей футболке' },
  { id: 70, type: 'photo', src: 'src/assets/70.jpg', caption: 'Просишь кофе' },
  { id: 71, type: 'photo', src: 'src/assets/71.jpg', caption: 'Лежим на пикнике' },
  { id: 72, type: 'photo', src: 'src/assets/72.jpg', caption: 'Челку укладываешь' },
  { id: 73, type: 'photo', src: 'src/assets/73.jpg', caption: 'Не получилось' },
  { id: 74, type: 'photo', src: 'src/assets/74.jpg', caption: 'Зато сфоткались' },
  { id: 75, type: 'photo', src: 'src/assets/75.jpg', caption: 'На моей день рождения со мной' },
  { id: 76, type: 'photo', src: 'src/assets/76.jpg', caption: 'И без меня' },
  { id: 77, type: 'photo', src: 'src/assets/77.jpg', caption: 'Во какие скулы сделали' },
  { id: 78, type: 'photo', src: 'src/assets/78.jpg', caption: 'Снова посадил за руль' },
  { id: 79, type: 'photo', src: 'src/assets/79.jpg', caption: 'Работаешь' },
  { id: 80, type: 'photo', src: 'src/assets/80.jpg', caption: 'работаешь' },
  { id: 81, type: 'photo', src: 'src/assets/81.jpg', caption: 'Подарил тебе медведя' },
  { id: 82, type: 'video', src: '/videos/82.mp4', caption: 'А ты мне красивое видео' },
  { id: 83, type: 'photo', src: 'src/assets/83.jpg', caption: 'Наелась и отдыхает' },
  { id: 84, type: 'photo', src: 'src/assets/84.jpg', caption: 'Телефон нюхаешь' },
  { id: 85, type: 'photo', src: 'src/assets/85.jpg', caption: 'Не понравилось' },
  { id: 86, type: 'photo', src: 'src/assets/86.jpg', caption: 'Сидим в KFC' },
  { id: 87, type: 'photo', src: 'src/assets/87.jpg', caption: 'Не понравилось как я тебя сфоткал' },
  { id: 88, type: 'photo', src: 'src/assets/88.jpg', caption: 'А тут все понравилось' },
  { id: 89, type: 'photo', src: 'src/assets/89.jpg', caption: 'И тут тоже' },
  { id: 90, type: 'photo', src: 'src/assets/90.jpg', caption: 'Ты у меня такая солидная' },
  { id: 91, type: 'photo', src: 'src/assets/91.jpg', caption: 'Эстетичная' },
  { id: 92, type: 'photo', src: 'src/assets/92.jpg', caption: 'Стильная' },
  { id: 93, type: 'photo', src: 'src/assets/93.jpg', caption: 'Элегантная' },
  { id: 94, type: 'photo', src: 'src/assets/94.jpg', caption: 'И самая красивая' },
  { id: 95, type: 'photo', src: 'src/assets/95.jpg', caption: 'Рыбка капля' },
  { id: 96, type: 'photo', src: 'src/assets/96.jpg', caption: 'Ну что, куколка?' },
  { id: 97, type: 'photo', src: 'src/assets/97.jpg', caption: 'Устала?' },
  { id: 98, type: 'photo', src: 'src/assets/98.jpg', caption: 'Или все супер?' },
  { id: 99, type: 'photo', src: 'src/assets/99.jpg', caption: 'А?!' },
  { id: 100, type: 'video', src: '/videos/100.mp4', caption: 'Жду твою реакцию' },
];